version: '3.4'

services:
  smrmsapi:
    image: phuckhangbui/smrms
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: api-container
    restart: unless-stopped
    ports:
      - '5000:5000'
    networks:
      - backend

  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: redis-container
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
