// <auto-generated />
using System;
using DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAO.Migrations
{
    [DbContext(typeof(MmrmsContext))]
    [Migration("20241018081610_addFieldIsFirstRentalPaymentContractPaymentTable")]
    partial class addFieldIsFirstRentalPaymentContractPaymentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<int?>("AccountBusinessId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirebaseMessageToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("LogId")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipRankId")
                        .HasColumnType("int");

                    b.Property<double?>("MoneySpent")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenDateExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRefresh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("MembershipRankId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("BusinessObject.AccountBusiness", b =>
                {
                    b.Property<int>("AccountBusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountBusinessId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountBusinessId");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.ToTable("AccountBusiness", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AddressBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("AddressId");

                    b.HasIndex("AccountId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponentId"));

                    b.Property<string>("ComponentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComponentId");

                    b.ToTable("Component", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ComponentProduct", b =>
                {
                    b.Property<int>("ComponentProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponentProductId"));

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsRequiredMoney")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComponentProductId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ProductId");

                    b.ToTable("ComponentProduct", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<string>("ContentBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentId");

                    b.ToTable("Content", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Contract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AccountSignId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSign")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DepositPrice")
                        .HasColumnType("float");

                    b.Property<int?>("NumberOfMonth")
                        .HasColumnType("int");

                    b.Property<double?>("RentPrice")
                        .HasColumnType("float");

                    b.Property<string>("RentingRequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalRentPrice")
                        .HasColumnType("float");

                    b.HasKey("ContractId");

                    b.HasIndex("AccountSignId");

                    b.HasIndex("RentingRequestId");

                    b.HasIndex("SerialNumber");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ContractPayment", b =>
                {
                    b.Property<int>("ContractPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractPaymentId"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CustomerPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsFirstRentalPayment")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SystemPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractPaymentId");

                    b.HasIndex("ContractId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("ContractPayment", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ContractTerm", b =>
                {
                    b.Property<int>("ContractTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractTermId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractTermId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractTerm", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateShip")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryId");

                    b.HasIndex("ContractId");

                    b.HasIndex("StaffId");

                    b.ToTable("Delivery", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DeliveryLog", b =>
                {
                    b.Property<int>("DeliveryLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryLogId"));

                    b.Property<int?>("AccountTriggerId")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryLogId");

                    b.HasIndex("AccountTriggerId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("DeliveryLog", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DigitalTransaction", b =>
                {
                    b.Property<string>("DigitalTransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PayOsOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DigitalTransactionId");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.ToTable("DigitalTransactions");
                });

            modelBuilder.Entity("BusinessObject.EmployeeTask", b =>
                {
                    b.Property<int>("EmployeeTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTaskId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceTicketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreviousTaskId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestResponseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeTaskId");

                    b.HasIndex("ContractId");

                    b.HasIndex("MaintenanceTicketId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("PreviousTaskId")
                        .IsUnique()
                        .HasFilter("[PreviousTaskId] IS NOT NULL");

                    b.HasIndex("RequestResponseId")
                        .IsUnique();

                    b.HasIndex("StaffId");

                    b.ToTable("EmployeeTask", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("AccountFeedbackId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("AccountFeedbackId");

                    b.HasIndex("ContractId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AccountPaidId")
                        .HasColumnType("int");

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<string>("DigitalTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintainTicketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayOsOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("AccountPaidId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BusinessObject.LogDetail", b =>
                {
                    b.Property<int>("LogDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogDetailId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.HasKey("LogDetailId");

                    b.HasIndex("AccountId");

                    b.ToTable("LogDetail", (string)null);
                });

            modelBuilder.Entity("BusinessObject.MaintenanceRequest", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ContractId");

                    b.ToTable("MaintenanceRequest", (string)null);
                });

            modelBuilder.Entity("BusinessObject.MaintenanceTicket", b =>
                {
                    b.Property<string>("MaintenanceTicketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("AdditionalFee")
                        .HasColumnType("float");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<double?>("ComponentPrice")
                        .HasColumnType("float");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRepair")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeTaskCreateId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductSerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceTicketId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ContractId");

                    b.HasIndex("EmployeeCreateId");

                    b.HasIndex("EmployeeTaskCreateId");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.HasIndex("ProductSerialNumber");

                    b.ToTable("MaintenanceTicket", (string)null);
                });

            modelBuilder.Entity("BusinessObject.MaintenanceTicketLog", b =>
                {
                    b.Property<int>("MaintenanceTicketLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceTicketLogId"));

                    b.Property<int?>("AccountTriggerId")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceTicketId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaintenanceTicketLogId");

                    b.HasIndex("AccountTriggerId");

                    b.HasIndex("MaintenanceTicketId");

                    b.ToTable("MaintenanceTicketLog", (string)null);
                });

            modelBuilder.Entity("BusinessObject.MembershipRank", b =>
                {
                    b.Property<int>("MembershipRankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipRankId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<string>("MembershipRankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MoneySpent")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MembershipRankId");

                    b.ToTable("MembershipRank", (string)null);
                });

            modelBuilder.Entity("BusinessObject.MembershipRankLog", b =>
                {
                    b.Property<int>("MembershipRankLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipRankLogId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembershipRankId")
                        .HasColumnType("int");

                    b.HasKey("MembershipRankLogId");

                    b.HasIndex("AccountId");

                    b.HasIndex("MembershipRankId");

                    b.ToTable("MembershipRankLog", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("AccountReceiveId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkForward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageNotification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.HasIndex("AccountReceiveId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<double?>("RentPrice")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductAttribute", b =>
                {
                    b.Property<int>("ProductAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductAttributeId"));

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductAttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttribute", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductComponentStatus", b =>
                {
                    b.Property<int>("ProductComponentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductComponentStatusId"));

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductComponentStatusId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("SerialNumber");

                    b.ToTable("ProductComponentStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<bool?>("IsThumbnail")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductTerm", b =>
                {
                    b.Property<int>("ProductTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTermId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTermId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTerm", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RentingRequest", b =>
                {
                    b.Property<string>("RentingRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AccountOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<bool?>("IsOnetimePayment")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfMonth")
                        .HasColumnType("int");

                    b.Property<double?>("ShippingPrice")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalDepositPrice")
                        .HasColumnType("float");

                    b.Property<double?>("TotalRentPrice")
                        .HasColumnType("float");

                    b.Property<double?>("TotalServicePrice")
                        .HasColumnType("float");

                    b.HasKey("RentingRequestId");

                    b.HasIndex("AccountOrderId");

                    b.ToTable("RentingRequest", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RentingRequestAddress", b =>
                {
                    b.Property<string>("RentingRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RentingRequestId");

                    b.ToTable("RentingRequestAddress", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RentingRequestProductDetail", b =>
                {
                    b.Property<int>("RentingRequestProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentingRequestProductDetailId"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RentingRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RentingRequestProductDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RentingRequestId");

                    b.ToTable("RentingRequestProductDetail", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RentingService", b =>
                {
                    b.Property<int>("RentingServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentingServiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RentingServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RentingServiceId");

                    b.ToTable("RentingService", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeTaskId")
                        .HasColumnType("int");

                    b.Property<string>("ReportContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("EmployeeTaskId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RequestResponse", b =>
                {
                    b.Property<int>("RequestResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestResponseId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateResponse")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeTaskId")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestResponseId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestResponse", (string)null);
                });

            modelBuilder.Entity("BusinessObject.SerialNumberProduct", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("ActualRentPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("RentTimeCounter")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("ProductId");

                    b.ToTable("SerialNumberProduct", (string)null);
                });

            modelBuilder.Entity("BusinessObject.SerialNumberProductLog", b =>
                {
                    b.Property<int>("SerialNumberProductLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerialNumberProductLogId"));

                    b.Property<int?>("AccountTriggerId")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumberProductLogId");

                    b.HasIndex("AccountTriggerId");

                    b.HasIndex("SerialNumber");

                    b.ToTable("SerialNumberProductLog", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ServiceRentingRequest", b =>
                {
                    b.Property<int>("ServiceRentingRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceRentingRequestId"));

                    b.Property<string>("RentingRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RentingServiceId")
                        .HasColumnType("int");

                    b.Property<double?>("ServicePrice")
                        .HasColumnType("float");

                    b.HasKey("ServiceRentingRequestId");

                    b.HasIndex("RentingRequestId");

                    b.HasIndex("RentingServiceId");

                    b.ToTable("ServiceRentingRequest", (string)null);
                });

            modelBuilder.Entity("BusinessObject.TaskLog", b =>
                {
                    b.Property<int>("TaskLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskLogId"));

                    b.Property<int?>("AccountTriggerId")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeTaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskLogId");

                    b.HasIndex("AccountTriggerId");

                    b.HasIndex("EmployeeTaskId");

                    b.ToTable("TaskLog", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TermId");

                    b.ToTable("Term", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.HasOne("BusinessObject.MembershipRank", "MembershipRank")
                        .WithMany("Accounts")
                        .HasForeignKey("MembershipRankId")
                        .HasConstraintName("FK_Account_MembershipRank");

                    b.Navigation("MembershipRank");
                });

            modelBuilder.Entity("BusinessObject.AccountBusiness", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithOne("AccountBusiness")
                        .HasForeignKey("BusinessObject.AccountBusiness", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AccountBusiness_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Address", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithMany("Addresses")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Address_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.ComponentProduct", b =>
                {
                    b.HasOne("BusinessObject.Component", "Component")
                        .WithMany("ComponentProducts")
                        .HasForeignKey("ComponentId")
                        .HasConstraintName("FK_ComponentProduct_ComponentID");

                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ComponentProducts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ComponentProduct_ProductID");

                    b.Navigation("Component");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.Contract", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountSign")
                        .WithMany("Contracts")
                        .HasForeignKey("AccountSignId")
                        .HasConstraintName("FK_Contract_Account");

                    b.HasOne("BusinessObject.RentingRequest", "RentingRequest")
                        .WithMany("Contracts")
                        .HasForeignKey("RentingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RentingRequest_Contract");

                    b.HasOne("BusinessObject.SerialNumberProduct", "ContractSerialNumberProduct")
                        .WithMany("Contracts")
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Contract_SerialNumberProduct");

                    b.Navigation("AccountSign");

                    b.Navigation("ContractSerialNumberProduct");

                    b.Navigation("RentingRequest");
                });

            modelBuilder.Entity("BusinessObject.ContractPayment", b =>
                {
                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("ContractPayments")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_ContractPayment_ContractID");

                    b.HasOne("BusinessObject.Invoice", "Invoice")
                        .WithMany("ContractPayments")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("FK_Invoice_ContractPayment");

                    b.Navigation("Contract");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BusinessObject.ContractTerm", b =>
                {
                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("ContractTerms")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_ContractTerm_ContractID");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BusinessObject.Delivery", b =>
                {
                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("Deliveries")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_Delivery_ContractID");

                    b.HasOne("BusinessObject.Account", "Staff")
                        .WithMany("Deliveries")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_Delivery_StaffID");

                    b.Navigation("Contract");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessObject.DeliveryLog", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountTrigger")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("AccountTriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DeliveryLog_AccountID");

                    b.HasOne("BusinessObject.Delivery", "Delivery")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("DeliveryId")
                        .HasConstraintName("FK_DeliveryLog_DeliveryID");

                    b.Navigation("AccountTrigger");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("BusinessObject.DigitalTransaction", b =>
                {
                    b.HasOne("BusinessObject.Invoice", "Invoice")
                        .WithOne("DigitalTransaction")
                        .HasForeignKey("BusinessObject.DigitalTransaction", "InvoiceId")
                        .HasConstraintName("FK_DigitalTransaction_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BusinessObject.EmployeeTask", b =>
                {
                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("EmployeeTasks")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_Task_Contract");

                    b.HasOne("BusinessObject.MaintenanceTicket", "MaintenanceTicket")
                        .WithMany("EmployeeTasks")
                        .HasForeignKey("MaintenanceTicketId")
                        .HasConstraintName("FK_MaintenanceTicketId_Task");

                    b.HasOne("BusinessObject.Account", "Manager")
                        .WithMany("TaskGaveList")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_Task_Manager");

                    b.HasOne("BusinessObject.EmployeeTask", "PreviousTask")
                        .WithOne()
                        .HasForeignKey("BusinessObject.EmployeeTask", "PreviousTaskId")
                        .HasConstraintName("FK_Task_PreviousTask");

                    b.HasOne("BusinessObject.RequestResponse", "RequestResponse")
                        .WithOne("EmployeeTask")
                        .HasForeignKey("BusinessObject.EmployeeTask", "RequestResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Task_Response");

                    b.HasOne("BusinessObject.Account", "Staff")
                        .WithMany("TaskReceivedList")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_Task_Staff");

                    b.Navigation("Contract");

                    b.Navigation("MaintenanceTicket");

                    b.Navigation("Manager");

                    b.Navigation("PreviousTask");

                    b.Navigation("RequestResponse");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessObject.Feedback", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountFeedback")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountFeedbackId")
                        .HasConstraintName("FK_Feedback_Account");

                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_Feedback_Contract");

                    b.Navigation("AccountFeedback");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BusinessObject.Invoice", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountPaid")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountPaidId")
                        .HasConstraintName("FK_Invoices_Account");

                    b.Navigation("AccountPaid");
                });

            modelBuilder.Entity("BusinessObject.LogDetail", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithMany("LogDetails")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_LogDetail_AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.MaintenanceRequest", b =>
                {
                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_MaintenanceRequest_Contract");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BusinessObject.MaintenanceTicket", b =>
                {
                    b.HasOne("BusinessObject.Component", "Component")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("ComponentId")
                        .HasConstraintName("FK_MaintenanceTicket_ComponentID");

                    b.HasOne("BusinessObject.Contract", "Contract")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK_MaintenanceTicket_ContractID");

                    b.HasOne("BusinessObject.Account", "EmployeeCreate")
                        .WithMany()
                        .HasForeignKey("EmployeeCreateId");

                    b.HasOne("BusinessObject.EmployeeTask", "EmployeeTaskCreate")
                        .WithMany("MaintenanceTicketsCreateFromTask")
                        .HasForeignKey("EmployeeTaskCreateId")
                        .HasConstraintName("FK_MaintenanceTicket_EmployeeTaskCreated");

                    b.HasOne("BusinessObject.Invoice", "Invoice")
                        .WithOne("MaintenanceTicket")
                        .HasForeignKey("BusinessObject.MaintenanceTicket", "InvoiceId")
                        .HasConstraintName("FK_Invoice_MaintainTicket");

                    b.HasOne("BusinessObject.SerialNumberProduct", "SerialNumberProduct")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("ProductSerialNumber")
                        .HasConstraintName("FK_MaintenanceTicket_SerialNumberProduct");

                    b.Navigation("Component");

                    b.Navigation("Contract");

                    b.Navigation("EmployeeCreate");

                    b.Navigation("EmployeeTaskCreate");

                    b.Navigation("Invoice");

                    b.Navigation("SerialNumberProduct");
                });

            modelBuilder.Entity("BusinessObject.MaintenanceTicketLog", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountTrigger")
                        .WithMany()
                        .HasForeignKey("AccountTriggerId");

                    b.HasOne("BusinessObject.MaintenanceTicket", "MaintenanceTicket")
                        .WithMany("MaintenanceTicketLogs")
                        .HasForeignKey("MaintenanceTicketId")
                        .HasConstraintName("FK_MaintenanceTicket_Log");

                    b.Navigation("AccountTrigger");

                    b.Navigation("MaintenanceTicket");
                });

            modelBuilder.Entity("BusinessObject.MembershipRankLog", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithMany("MembershipRankLogs")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_account_membershiplog");

                    b.HasOne("BusinessObject.MembershipRank", "MembershipRank")
                        .WithMany("MembershipRankLogs")
                        .HasForeignKey("MembershipRankId")
                        .HasConstraintName("FK_MembershipRank_membershiplog");

                    b.Navigation("Account");

                    b.Navigation("MembershipRank");
                });

            modelBuilder.Entity("BusinessObject.Notification", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountReceive")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountReceiveId")
                        .HasConstraintName("FK_Notification_Account");

                    b.Navigation("AccountReceive");
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.HasOne("BusinessObject.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Product_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObject.ProductAttribute", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Attribute_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.ProductComponentStatus", b =>
                {
                    b.HasOne("BusinessObject.ComponentProduct", "Component")
                        .WithMany("ProductComponentStatuses")
                        .HasForeignKey("ComponentId")
                        .HasConstraintName("FK_ProductComponentStatus_ComponentID");

                    b.HasOne("BusinessObject.SerialNumberProduct", "SerialNumberProduct")
                        .WithMany("ProductComponentStatuses")
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ProductComponentStatus_SerialNumberProduct");

                    b.Navigation("Component");

                    b.Navigation("SerialNumberProduct");
                });

            modelBuilder.Entity("BusinessObject.ProductImage", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ProductImage_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.ProductTerm", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ProductTerms")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Term_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.RentingRequest", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountOrder")
                        .WithMany("RentingRequests")
                        .HasForeignKey("AccountOrderId")
                        .HasConstraintName("FK_RentingRequest_Account");

                    b.Navigation("AccountOrder");
                });

            modelBuilder.Entity("BusinessObject.RentingRequestAddress", b =>
                {
                    b.HasOne("BusinessObject.RentingRequest", "RentingRequest")
                        .WithOne("RentingRequestAddress")
                        .HasForeignKey("BusinessObject.RentingRequestAddress", "RentingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_RentingRequest_RentingRequestAddress");

                    b.Navigation("RentingRequest");
                });

            modelBuilder.Entity("BusinessObject.RentingRequestProductDetail", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("RentingRequestProductDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_RentingRequestProductDetail_Product");

                    b.HasOne("BusinessObject.RentingRequest", "RentingRequest")
                        .WithMany("RentingRequestProductDetails")
                        .HasForeignKey("RentingRequestId")
                        .HasConstraintName("FK_RentingRequestProductDetail_RentingRequest");

                    b.Navigation("Product");

                    b.Navigation("RentingRequest");
                });

            modelBuilder.Entity("BusinessObject.Report", b =>
                {
                    b.HasOne("BusinessObject.EmployeeTask", "EmployeeTask")
                        .WithMany("Reports")
                        .HasForeignKey("EmployeeTaskId")
                        .HasConstraintName("FK_Report_TaskID");

                    b.Navigation("EmployeeTask");
                });

            modelBuilder.Entity("BusinessObject.RequestResponse", b =>
                {
                    b.HasOne("BusinessObject.MaintenanceRequest", "Request")
                        .WithMany("RequestResponses")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_RequestResponse_MaintenanceRequest");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BusinessObject.SerialNumberProduct", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("SerialNumberProducts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductNumber_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.SerialNumberProductLog", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountTrigger")
                        .WithMany("SerialNumberProductLogs")
                        .HasForeignKey("AccountTriggerId")
                        .HasConstraintName("FK_SerialNumberProductLog_AccountID");

                    b.HasOne("BusinessObject.SerialNumberProduct", "SerialNumberProduct")
                        .WithMany("SerialNumberProductLogs")
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_SerialNumberProduct_Log");

                    b.Navigation("AccountTrigger");

                    b.Navigation("SerialNumberProduct");
                });

            modelBuilder.Entity("BusinessObject.ServiceRentingRequest", b =>
                {
                    b.HasOne("BusinessObject.RentingRequest", "RentingRequest")
                        .WithMany("ServiceRentingRequests")
                        .HasForeignKey("RentingRequestId")
                        .HasConstraintName("FK_servicerequest_rentingrequest");

                    b.HasOne("BusinessObject.RentingService", "RentingService")
                        .WithMany("ServiceRentingRequests")
                        .HasForeignKey("RentingServiceId")
                        .HasConstraintName("FK_rentingservice_servicerequest");

                    b.Navigation("RentingRequest");

                    b.Navigation("RentingService");
                });

            modelBuilder.Entity("BusinessObject.TaskLog", b =>
                {
                    b.HasOne("BusinessObject.Account", "AccountTrigger")
                        .WithMany("TaskLogs")
                        .HasForeignKey("AccountTriggerId")
                        .HasConstraintName("FK_TaskLog_AccountID");

                    b.HasOne("BusinessObject.EmployeeTask", "EmployeeTask")
                        .WithMany("TaskLogs")
                        .HasForeignKey("EmployeeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TaskLog_TaskID");

                    b.Navigation("AccountTrigger");

                    b.Navigation("EmployeeTask");
                });

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.Navigation("AccountBusiness");

                    b.Navigation("Addresses");

                    b.Navigation("Contracts");

                    b.Navigation("Deliveries");

                    b.Navigation("DeliveryLogs");

                    b.Navigation("Feedbacks");

                    b.Navigation("Invoices");

                    b.Navigation("LogDetails");

                    b.Navigation("MembershipRankLogs");

                    b.Navigation("Notifications");

                    b.Navigation("RentingRequests");

                    b.Navigation("SerialNumberProductLogs");

                    b.Navigation("TaskGaveList");

                    b.Navigation("TaskLogs");

                    b.Navigation("TaskReceivedList");
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessObject.Component", b =>
                {
                    b.Navigation("ComponentProducts");

                    b.Navigation("MaintenanceTickets");
                });

            modelBuilder.Entity("BusinessObject.ComponentProduct", b =>
                {
                    b.Navigation("ProductComponentStatuses");
                });

            modelBuilder.Entity("BusinessObject.Contract", b =>
                {
                    b.Navigation("ContractPayments");

                    b.Navigation("ContractTerms");

                    b.Navigation("Deliveries");

                    b.Navigation("EmployeeTasks");

                    b.Navigation("Feedbacks");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceTickets");
                });

            modelBuilder.Entity("BusinessObject.Delivery", b =>
                {
                    b.Navigation("DeliveryLogs");
                });

            modelBuilder.Entity("BusinessObject.EmployeeTask", b =>
                {
                    b.Navigation("MaintenanceTicketsCreateFromTask");

                    b.Navigation("Reports");

                    b.Navigation("TaskLogs");
                });

            modelBuilder.Entity("BusinessObject.Invoice", b =>
                {
                    b.Navigation("ContractPayments");

                    b.Navigation("DigitalTransaction");

                    b.Navigation("MaintenanceTicket");
                });

            modelBuilder.Entity("BusinessObject.MaintenanceRequest", b =>
                {
                    b.Navigation("RequestResponses");
                });

            modelBuilder.Entity("BusinessObject.MaintenanceTicket", b =>
                {
                    b.Navigation("EmployeeTasks");

                    b.Navigation("MaintenanceTicketLogs");
                });

            modelBuilder.Entity("BusinessObject.MembershipRank", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("MembershipRankLogs");
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.Navigation("ComponentProducts");

                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductTerms");

                    b.Navigation("RentingRequestProductDetails");

                    b.Navigation("SerialNumberProducts");
                });

            modelBuilder.Entity("BusinessObject.RentingRequest", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("RentingRequestAddress");

                    b.Navigation("RentingRequestProductDetails");

                    b.Navigation("ServiceRentingRequests");
                });

            modelBuilder.Entity("BusinessObject.RentingService", b =>
                {
                    b.Navigation("ServiceRentingRequests");
                });

            modelBuilder.Entity("BusinessObject.RequestResponse", b =>
                {
                    b.Navigation("EmployeeTask");
                });

            modelBuilder.Entity("BusinessObject.SerialNumberProduct", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MaintenanceTickets");

                    b.Navigation("ProductComponentStatuses");

                    b.Navigation("SerialNumberProductLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
