name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_KHANG_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KHANG_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --no-cache --build-arg CACHEBUST=$(date +%s) -t phuckhangbui/smrms .

      - name: Push Docker Image
        run: |
          docker push phuckhangbui/smrms

  deploy-to-droplet:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Droplet and login to Docker Hub
        uses: fifsky/ssh-action@master
        with:
          command: |
            echo ${{ secrets.DOCKERHUB_KHANG_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_KHANG_USERNAME }} --password-stdin
            docker pull phuckhangbui/smrms:latest
            docker ps -q --filter "name=server" && docker stop server && docker rm server
            docker run -d --name server --network host -p 5000:5000 -e TZ=Asia/Ho_Chi_Minh phuckhangbui/smrms:latest
          host: ${{ secrets.DROPLET_SSH_HOST }}
          user: ${{ secrets.DROPLET_SSH_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          args: '-tt -vvv'

